name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti jika kamu pakai branch selain "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to public repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git clone git@github.com:FazriFirdaus/hedensoderr.git public
          rsync -av --progress ./ ./public --exclude .git --exclude public
          cd public
          git add .
          git commit -m "Auto deploy from private repo" || echo "Nothing to commit"
          git push origin main
